allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.38.0'
  - '@tscircuit/capacity-autorouter@0.0.614'
  - '@tscircuit/copper-pour-solver@0.0.35'
  - '@tscircuit/core@0.0.1361'
  - '@tscircuit/matchpack@0.0.29'
  - '@tscircuit/props@0.0.557'
  - '@tscircuit/schematic-trace-solver@0.0.73'
  - posthog-js@1.395.0
  - '@tscircuit/capacity-autorouter@0.0.640'
  - '@tscircuit/cli@0.1.1617'
  - '@tscircuit/core@0.0.1403'
  - '@tscircuit/eval@0.0.979'
  - '@tscircuit/matchpack@0.0.31'
  - '@tscircuit/runframe@0.0.2171'
  - schematic-symbols@0.0.231
  - tscircuit@0.0.2017
