[project]
name = "virtual-hardware-laboratary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.21",
    "fastapi==0.110.0",
    "openhands-sdk",
    "openhands-tools",
    "python-dotenv>=1.2.1",
    "ana",
    "ana-mcp-server",
    "vhl-protocol",
    "aosm",
]

[tool.uv.workspace]
members = [
    "agent-sdk/openhands-sdk",
    "agent-sdk/openhands-tools",
    "ana-mcp-server",
    "ana",
    "vhl_protocol",
    "aosm",
]

[tool.uv.sources]
openhands-sdk = { workspace = true }
openhands-tools = { workspace = true }
ana-mcp-server = { workspace = true }
ana = { workspace = true }
vhl-protocol = { workspace = true }
aosm = { workspace = true }