[project]
name = "virtual-hardware-laboratary"
version = "0.1.0"
description = "Hardware laboratory for AI agents "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.21",
    "google-cloud-aiplatform>=1.38",
    "openhands-sdk",
    "openhands-tools",
    "google-cloud-storage>=2.14.0",
    "python-dotenv>=1.2.1",
    "ana",
    "vhl-protocol",
    "vhl-workspace",
    "aosm",
    "archy",
    "librarian",
    "litellm",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "vhl-common",
    "pytest-html>=4.2.0",
]

[project.optional-dependencies]
docs = [
    "sphinx>=7.0.0",
    "myst-parser>=2.0.0",
    "sphinx-rtd-theme>=2.0.0",
]

[tool.uv.workspace]
members = [
    "ana",
    "vhl_protocol",
    "workspace",
    "aosm",
    "archy",
    "librarian",
    "vhl_common",
]

[tool.uv.sources]
litellm = { git = "https://github.com/vivekvjnk/litellm.git", branch = "fix/vertex-gemini-multimodal-drop" }
openhands-sdk = { git = "https://github.com/vivekvjnk/agent-sdk.git", branch = "feat/escalate_tool", subdirectory = "openhands-sdk" }
openhands-tools = { git = "https://github.com/vivekvjnk/agent-sdk.git", branch = "feat/escalate_tool", subdirectory = "openhands-tools" }

ana = { workspace = true }
vhl-protocol = { workspace = true }
vhl-workspace = { workspace = true }
aosm = { workspace = true }
archy = { workspace = true }
librarian = { workspace = true }
vhl-common = { workspace = true }

[tool.uv]
override-dependencies = [
    "litellm @ git+https://github.com/vivekvjnk/litellm.git@fix/vertex-gemini-multimodal-drop"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
asyncio_mode = "auto"
addopts = "--html=tests/archy/report.html --self-contained-html"
