[project]
name = "ana"
version = "0.1.0"
description = "ANA for Virtual Hardware Laboratory"
dependencies = [
    "pydantic",
    "mcp",
    "httpx",
    "vhl-common",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.packages.find]
where = ["."]
include = ["ana_agent*"]


[tool.uv.sources]
ana_worker_1 = {workspace = true}
ana_worker_2 = {workspace = true}
state_machine = {workspace = true}