[project]
name = "archy"
version = "0.1.0"
description = "Archy for Virtual Hardware Laboratory"
dependencies = [
    "pydantic",
    "mcp",
    "httpx",
    "setuptools",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.packages.find]
where = ["."]
include = ["archy_agent*"]

